[default]
service_name = "oai-enricher-service"
#FastAPI
fastapi_title = "OAI Enricher Service"
fastapi_description = ""


log_file = "@format {env[BASE_DIR]}/logs/oes.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"

expose_port = 3947
oltp_grpc_eindpoint = "http://tempo:4317"
target_one_host = "app-b"
target_second_host = "app-c"